# Simple workflow for deploying static content to GitHub Pages
name: Build LaTeX

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['master']
    paths:
        - src/data.ts
        - src/texify.ts

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run texify
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            *.tex
          post_compile: |
            mv *.pdf public/
      - name: Commit files
        run: |
          git config --local user.email "dev.jakubrada@icloud.com"
          git config --local user.name "Jakub Rada[bot]"
          git add *.pdf
          git commit -m "Generate PDF files"
      - name: Push changes
        uses: ad-m/github-push-action@master
